New version of data backup
ubvu/open-handbook pull request #140
Opened 2024-09-06 12:36 UTC by jensdebruijn

Some of this text was already under data protection, but I have tried to write this as a much more accessible and actionable version of part of this document specifically focused on data backup. Let me know if there is any feedback!

2024-09-16 18:12 UTC, chartgerink commented
Thanks @jensdebruijn – we are currently not adding new topics for the moment, until we [finish the current milestone](https://github.com/ubvu/open-handbook/milestone/1).

Could you share where this text was lifted from? Or I may misunderstand and this is actually new text?

2024-09-26 12:40 UTC, jensdebruijn commented
This is new text. Can it be added after the suggested milestone?

2024-09-27 10:05 UTC, chartgerink commented
We will revisit this after the current milestone 👍 Thanks for opening the PR regardless 😊

2024-10-07 09:59 UTC, Karvovskaya requested changes
Jens, I am wondering if we can add Teams/Sharepoint to OneDrvie section so that we don't encourage researchers to only use their personal storage - see here https://ubvu.github.io/open-handbook/topics/data-storage.html What do you think? Does it make sense from your work perspective or is everyone just using OneDrive?

2024-10-30 18:21 UTC, chartgerink commented
Hi :wave: We will need a response on this to carry this forward. @jensdebruijn could you please reply in the next week (so by Thursday November 7th)?

If we don't receive a response, we will have to close this PR for now as we don't really see how it fits in right now. I agree data backup is a good idea, and will port this over to a topic and link back to this PR for later handling 👍

2024-11-19 10:56 UTC, peer35 commented
OneDrive is a syncing solution: an easy way to share files across different devices, it is not a backup solution! Accidentally deleting files and folders from your laptop will also remove them online, versioning does not offer complete protection from that. 

The sync mechanism can also be unstable for example when working with large amounts of folders.

Another downside of OneDrive is that it is personal, once you leave the VU the researcher and colleagues lose access to the files.

MS Teams is group-based but has the disadvantage that file management is difficult or even impossible when using Linux.

There is nothing wrong with these tools and it is certainly good practice to store your documents on Teams or OneDrive instead of only on your laptop, but researchers should understand the limitations.

In case of valuable research data researchers should always store a copy on one of the preferred storage solutions: Yoda, Research Drive or SciStor. Data on these platforms is automatically backed up and remains accessible when a research leaves the VU.

2024-11-20 09:41 UTC, Karvovskaya commented
Thank you all for the comments! I think the point about "accidentally deleting files and folders" is a very important one. Brett often tells me that a good backup system protects your work from yourself. This is an argument for having some storage place in addition to the cloud.
I know that Brett uses this resource on backup in his training https://geo-data-support.sites.uu.nl/data-management/data-backup/

2024-11-28 09:50 UTC, Karvovskaya commented
I rewrote the text and would love someone's opinion on this! @peer35?

2025-01-16 10:51 UTC, chartgerink approved these changes
Perfect - i made some last changes to get everything up to spec but it's ready to merge 👍

2025-01-16 10:56 UTC, merged