include better irods description
ubvu/open-handbook pull request #263
Opened 2024-11-12 13:55 UTC by jensdebruijn

This updates the description of iRods to a much more usable version

2024-11-18 10:00 UTC, peer35 requested changes
Thanks! This is indeed an improvement. I've requested two small changes

2024-11-18 10:00 UTC, peer35 commented on topics/bazis.qmd
> +      "irods_user_name": "<YOUR-VUNETID>@vu.nl",
That should be the users email address. Change to `<email address>`

2024-11-18 10:00 UTC, peer35 commented on topics/bazis.qmd
> +This will show you the contents of your home directory on Yoda. The project folder you have access to is located at `/vu/home`.
Can be plural: "The project folders you have access to are located at `/vu/home`"

2024-11-19 10:57 UTC, peer35 approved these changes

2024-11-19 10:58 UTC, peer35 approved these changes
Looks fine now.

2024-11-20 09:27 UTC, Karvovskaya approved these changes

2024-11-26 08:29 UTC, chartgerink approved these changes

2024-11-27 08:55 UTC, merged