Yoda topic
ubvu/open-handbook pull request #270
Opened 2024-11-20 09:13 UTC by peer35

Yoda topic page based on the text on https://yoda.vu.nl 
#92 #252

2024-11-20 09:32 UTC, jhrudey approved these changes
Looks good. My only thought is whether its a bit too long or whether there is a way to utilize the iFrame concept to copy over an existing section from the yoda.vu.nl page so that we don't have two separate pages to keep up to date. In other words, perhaps have a brief intro on this page then immediate iFrame to this page https://yoda.vu.nl/site/ that provides the same overview. And finish with the same references at the end. Just my thoughts.

2024-11-20 11:01 UTC, peer35 commented
Agreed that repeating the same content is not great, but the plan is that the UU Yoda site will replace yoda.vu.nl next year. That means this topic would be the main place for a VU-centered description with a link to the UU Yoda site for more information.

Once the UU site is finished there will probably be some VU-specific Yoda content left that doesn't fit in the UU site. We haven't decided yet where that should go, but I don't want to maintain the Yoda github site just for a few pages. Maybe it will fit a "Yoda guide" in the handbook.

2024-11-20 12:06 UTC, jhrudey commented
Ok! In that case, ignore my previous comment. Makes sense not to have the separate github site just for that

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: Peter Vos ***@***.***>
Verzonden: Wednesday, November 20, 2024 12:01:54 PM
Aan: ubvu/open-handbook ***@***.***>
CC: Hrudey, E.J. (Jessica) ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [ubvu/open-handbook] Yoda topic (PR #270)


Agreed that repeating the same content is not great, but the plan is that the UU Yoda site will replace yoda.vu.nl next year. That means this topic would be the main place for a VU-centered description with a link to the UU Yoda site for more information.

Once the UU site is finished there will probably be some VU-specific Yoda content left that doesn't fit in the UU site. We haven't decided yet where that should go, but I don't want to maintain the Yoda github site just for a few pages. Maybe it will fit a "Yoda guide" in the handbook.

—
Reply to this email directly, view it on GitHub<https://github.com/ubvu/open-handbook/pull/270#issuecomment-2488274521>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AIOIPE3DVUIH2XDIGJ65DN32BRT2FAVCNFSM6AAAAABSECI372VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIOBYGI3TINJSGE>.
You are receiving this because you commented.Message ID: ***@***.***>

2024-11-28 10:42 UTC, Karvovskaya approved these changes

2024-11-28 10:42 UTC, merged

2024-11-28 11:01 UTC, Jolien-S requested changes
Like Peter explained, I think it's useful to have some basic information about Yoda in the handbook. I requested a few changes, after which this topic can be included in the handbook.

2024-11-28 11:01 UTC, Jolien-S commented on topics/yoda.qmd
> +The following features make Yoda particularly attractive for researchers (end-users):
Should we add the advantage of being able to invite both VU-internal and external colleagues to a Yoda project space? I guess it's kind of implied in the final bullet point, but I think it's useful for researchers to have this explicit.